// <auto-generated />
namespace TrabajoFinal.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class columnas_nuevas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnas_nuevas));
        
        string IMigrationMetadata.Id
        {
            get { return "201905312204387_columnas_nuevas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
